### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by mgalloy** [GPUE-group/GPUE#12]
A set of guidelines for contributing would make contributions easier for both the maintainers and the potential contributors. See the [GitHub docs](https://help.github.com/articles/setting-guidelines-for-repository-contributors) for examples.

**Comment by leios** [comment]
Simple contribution guidelines have been added here: https://github.com/GPUE-group/GPUE/blob/master/CONTRIBUTING.md

**Comment by mgalloy** [comment]
Great! I believe this satisfies the review requirements. I will check off that requirement, you can close this ticket.
