### ISSUE TITLE
Convergence criteria for imaginary time propagation

### ISSUE THREAD

**Issue by AllenNC** [GPUE-group/GPUE#34]
A feature in the ground state calculation that stops the imaginary time propagation when the wave function converges (for instance, stoping the calculation when the maximum difference of the wave function or energy difference between the previous step and the current step is less then a certain value). 

As Leios pointed out, it would require running the energy calculation and watching it until it levels out. I wonder if it'll be better if the energy is calculated per 100 loops (or something like that) since the energy calculation is quite time consuming as far as I know. 

Thanks!

**Comment by leios** [comment]
The energy calc isn's so bad anymore (it's all on the GPU now). The primary problem is that it uses an auxiliary array which wastes a bit of GPU memory. It's not a huge deal, but if your wavefunction is huge, it can break.

Thanks for submitting the issue! I'll get on it soon.

**Comment by leios** [comment]
Hey @AllenNC, sorry it took us a while to get to this Issue. I am still working on the multicomp stuff, but got swept up in paper and thesis writing along with travel. It looks like this issue has been fixed with PR #35. Thanks for the suggestion!
