### ISSUE TITLE
Change build system to CMake instead of Makefile

### ISSUE THREAD

**Issue by mlxd** [GPUE-group/GPUE#4]
Allows for more automated building of GPUE

**Comment by leios** [comment]
A simple cmake file has been created for GPUE hough branch. It was my first attempt, so there are probably issues with it.

https://github.com/GPUE-group/GPUE/commit/992c4ad6fc4849c1eb6e68f7a5fa17fed6a1a09b

**Comment by mlxd** [comment]
CMake file seems to work fine. Closing issue.
